-- Generated by Noctalia user-templates

local colors = {
	bg = "{{colors.surface.default.hex}}",
	bg_alt = "{{colors.surface_container.default.hex}}",
	bg_high = "{{colors.surface_container_high.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
	fg_dim = "{{colors.on_surface_variant.default.hex}}",
	fg_muted = "{{colors.outline.default.hex}}",
	primary = "{{colors.primary.default.hex}}",
	secondary = "{{colors.secondary.default.hex}}",
	tertiary = "{{colors.tertiary.default.hex}}",
	error = "{{colors.error.default.hex}}",
}

return {
	normal = {
		a = { fg = colors.bg, bg = colors.primary, gui = "bold" },
		b = { fg = colors.fg, bg = colors.bg_alt },
		c = { fg = colors.fg_dim, bg = colors.bg_alt },
	},
	insert = {
		a = { fg = colors.bg, bg = colors.secondary, gui = "bold" },
		b = { fg = colors.fg, bg = colors.bg_alt },
		c = { fg = colors.fg_dim, bg = colors.bg_alt },
	},
	visual = {
		a = { fg = colors.bg, bg = colors.tertiary, gui = "bold" },
		b = { fg = colors.fg, bg = colors.bg_alt },
		c = { fg = colors.fg_dim, bg = colors.bg_alt },
	},
	replace = {
		a = { fg = colors.bg, bg = colors.error, gui = "bold" },
		b = { fg = colors.fg, bg = colors.bg_alt },
		c = { fg = colors.fg_dim, bg = colors.bg_alt },
	},
	command = {
		a = { fg = colors.bg, bg = colors.primary, gui = "bold" },
		b = { fg = colors.fg, bg = colors.bg_alt },
		c = { fg = colors.fg_dim, bg = colors.bg_alt },
	},
	inactive = {
		a = { fg = colors.fg_muted, bg = colors.bg },
		b = { fg = colors.fg_muted, bg = colors.bg },
		c = { fg = colors.fg_muted, bg = colors.bg },
	},
}
