-- Generated by Noctalia user-templates

return {
	bg = "{{colors.surface.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
	yellow = "{{colors.tertiary.default.hex}}",
	cyan = "{{colors.secondary.default.hex}}",
	darkblue = "{{colors.primary.default.hex}}",
	green = "{{colors.secondary.default.hex}}",
	orange = "{{colors.tertiary.default.hex}}",
	violet = "{{colors.tertiary_fixed_dim.default.hex}}",
	magenta = "{{colors.secondary_fixed_dim.default.hex}}",
	blue = "{{colors.primary_fixed_dim.default.hex}}",
	red = "{{colors.error.default.hex}}",
}
