{ pkgs, vscode-extensions }:
with vscode-extensions; [
  aaron-bond.better-comments
  adpyke.vscode-sql-formatter
  alefragnani.Bookmarks
  alefragnani.project-manager
  AnandKothari.petals-pastels
  antfu.slidev
  AyakoSky.sodagreen-theme
  bierner.markdown-mermaid
  biomejs.biome
  bpruitt-goddard.mermaid-markdown-syntax-highlighting
  BrandonKirbyson.vscode-animations
  Cameron.vscode-pytest
  Catppuccin.catppuccin-vsc
  Catppuccin.catppuccin-vsc-icons
  charliermarsh.ruff
  chrisdicarlo.vscode-switch-git-worktree
  chrisjsewell.gulp-lattice
  christian-kohler.path-intellisense
  codezombiech.gitignore
  coolbear.systemd-unit-file
  dbaeumer.vscode-eslint
  denoland.vscode-deno
  DEVSENSE.composer-php-vscode
  DEVSENSE.phptools-vscode
  DiemasMichiels.emulate
  diff001a.kawaii-theme
  doggy8088.quicktype-refresh
  dsznajder.es7-react-js-snippets
  eamodio.gitlens
  EditorConfig.EditorConfig
  esbenp.prettier-vscode
  formulahendry.auto-close-tag
  formulahendry.auto-rename-tag
  fwcd.kotlin
  GitHub.copilot
  GitHub.copilot-chat
  github.vscode-github-actions
  GitHub.vscode-pull-request-github
  glenn2223.live-sass
  GrapeCity.gc-excelviewer
  GregorBiswanger.json2ts
  Gruntfuggly.todo-tree
  hediet.vscode-drawio
  hogashi.crontab-syntax-highlight
  Horla.horla-light-theme
  humao.rest-client
  IBM.output-colorizer
  idleberg.applescript
  jakearl.search-editor-apply-changes
  James-Yu.latex-workshop
  janisdd.vscode-edit-csv
  jock.svg
  joekon.ssmacro
  jonkwheeler.styled-components-snippets
  Joundy.lumpat
  juggernautjp.less-toml
  KacperBiedka.one-candy-dark
  koehlma.markdown-math
  liviuschera.noctis
  loiane.ts-extension-pack
  mads-hartmann.bash-ide-vscode
  manuthebyte.dynamic-icon-theme
  marp-team.marp-vscode
  matangover.mypy
  mechatroner.rainbow-csv
  mhutchie.git-graph
  mrmlnc.vscode-duplicate
  ms-azuretools.vscode-containers
  ms-azuretools.vscode-docker
  MS-CEINTL.vscode-language-pack-ja
  ms-playwright.playwright
  ms-python.black-formatter
  ms-python.debugpy
  ms-python.flake8
  ms-python.python
  ms-python.vscode-pylance
  ms-toolsai.jupyter
  ms-toolsai.jupyter-keymap
  ms-toolsai.jupyter-renderers
  ms-toolsai.vscode-jupyter-cell-tags
  ms-toolsai.vscode-jupyter-slideshow
  ms-vscode-remote.remote-containers
  ms-vscode-remote.remote-ssh
  ms-vscode-remote.remote-ssh-edit
  ms-vscode-remote.remote-wsl
  ms-vscode-remote.vscode-remote-extensionpack
  ms-vscode.remote-explorer
  ms-vscode.remote-server
  msjsdiag.vscode-react-native
  mxsdev.typescript-explorer
  naumovs.color-highlight
  neilbrayfield.php-docblocker
  njpwerner.autodocstring
  nmsmith89.incrementor
  nrwl.angular-console
  oderwat.indent-rainbow
  pAIrprog.ui-sketcher
  pamaron.pytest-runner
  peakchen90.open-html-in-browser
  PKief.material-icon-theme
  pmneo.tsimporter
  pranaygp.vscode-css-peek
  Prisma.prisma
  PulkitGangwar.nextjs-snippets
  redhat.java
  redhat.vscode-yaml
  ritwickdey.LiveServer
  rust-lang.rust-analyzer
  ryu1kn.partial-diff
  ryuta46.multi-command
  sazumiviki.kawaine-theme
  seatonjiang.gitmoji-vscode
  shakram02.bash-beautify
  shardulm94.trailing-spaces
  shd101wyy.markdown-preview-enhanced
  soft-aesthetic.soft-era-theme
  steoates.autoimport
  streetsidesoftware.code-spell-checker
  stringham.move-ts
  styled-components.vscode-styled-components
  subframe7536.custom-ui-style
  sukumo28.wav-preview
  tamasfe.even-better-toml
  tauri-apps.tauri-vscode
  TheHelpfulTipper.pinkpanda-dark-theme
  toba.vsfire
  tomoki1207.pdf
  TomPollak.lazygit-vscode
  TomRijndorp.find-it-faster
  Tyriar.luna-paint
  vincaslt.highlight-matching-tag
  VisualStudioExptTeam.intellicode-api-usage-examples
  VisualStudioExptTeam.vscodeintellicode
  vscjava.vscode-gradle
  vscjava.vscode-java-debug
  vscjava.vscode-java-dependency
  vscjava.vscode-java-pack
  vscjava.vscode-java-test
  vscjava.vscode-maven
  vscodevim.vim
  VSpaceCode.whichkey
  xabikos.JavaScriptSnippets
  yzhang.markdown-all-in-one
  Zignd.html-css-class-completion
  zokugun.cron-tasks
]
