# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@modelcontextprotocol/sdk-0.6.1" = {
      name = "_at_modelcontextprotocol_slash_sdk";
      packageName = "@modelcontextprotocol/sdk";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@modelcontextprotocol/sdk/-/sdk-0.6.1.tgz";
        sha512 = "OkVXMix3EIbB5Z6yife2XTrSlOnVvCLR1Kg91I4pYFEsV9RbnoyQVScXCuVhGaZHOnTZgso8lMQN1Po2TadGKQ==";
      };
    };
    "@types/pegjs-0.10.6" = {
      name = "_at_types_slash_pegjs";
      packageName = "@types/pegjs";
      version = "0.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pegjs/-/pegjs-0.10.6.tgz";
        sha512 = "eLYXDbZWXh2uxf+w8sXS8d6KSoXTswfps6fvCUuVAGN8eRpfe7h9eSRydxiSJvo9Bf+GzifsDOr9TMQlmJdmkw==";
      };
    };
    "aws-ssl-profiles-1.1.2" = {
      name = "aws-ssl-profiles";
      packageName = "aws-ssl-profiles";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-ssl-profiles/-/aws-ssl-profiles-1.1.2.tgz";
        sha512 = "NZKeq9AfyQvEeNlN0zSYAaWrmBffJh3IELMZfRpJVWgrpEbtEpnjvzqBPf+mxoI287JohRDoa+/nsfqqiZmF6g==";
      };
    };
    "big-integer-1.6.52" = {
      name = "big-integer";
      packageName = "big-integer";
      version = "1.6.52";
      src = fetchurl {
        url = "https://registry.npmjs.org/big-integer/-/big-integer-1.6.52.tgz";
        sha512 = "QxD8cf2eVqJOOz63z6JIN9BzvVs/dlySa5HGSBH5xtR8dPteIRQnBxxKqkNTiT6jbDTF6jAfrd4oMcND9RGbQg==";
      };
    };
    "bytes-3.1.2" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.1.2.tgz";
        sha512 = "/Nf7TyzTx6S3yRJObOAV7956r8cr2+Oj8AC5dt8wSP3BQAoeX58NoHyCU8P8zGkNXStjTSi6fzO6F0pBdcYbEg==";
      };
    };
    "content-type-1.0.5" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz";
        sha512 = "nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==";
      };
    };
    "denque-2.1.0" = {
      name = "denque";
      packageName = "denque";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/denque/-/denque-2.1.0.tgz";
        sha512 = "HVQE3AAb/pxF8fQAoiqpvg9i3evqug3hoiwakOyZAwJm+6vZehbkYXZ0l4JxS+I3QxM97v5aaRNhj8v5oBhekw==";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "generate-function-2.3.1" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.3.1.tgz";
        sha512 = "eeB5GfMNeevm/GRYq20ShmsaGcmI81kIX2K9XQx5miC8KdHaC6Jm0qQ8ZNeGOi7wYB8OsdxKs+Y2oVuTFuVwKQ==";
      };
    };
    "http-errors-2.0.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-2.0.0.tgz";
        sha512 = "FtwrG/euBzaEjYeRqOgly7G0qviiXoJWnvEH2Z1plBdXgbyjv34pHTSb9zoeHMyDy33+DWy5Wt9Wo+TURtOYSQ==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha512 = "Ks/IoX00TtClbGQr4TWXemAnktAQvYB7HzcCxDGqEZU6oCmb2INHuOoKxbtR+HFkmYWBKv/dOZtGRiAjDhj92g==";
      };
    };
    "long-5.3.2" = {
      name = "long";
      packageName = "long";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/long/-/long-5.3.2.tgz";
        sha512 = "mNAgZ1GmyNhD7AuqnTG3/VQ26o760+ZYBPKjPvugO8+nLbYfX6TVpJPseBvopbdY+qpZ/lKUnmEc1LeZYS3QAA==";
      };
    };
    "lru-cache-7.18.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "7.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-7.18.3.tgz";
        sha512 = "jumlc0BIUrS3qJGgIkWZsyfAM7NCWiBcCDhnd+3NNM5KbBmLTgHVfWBcg6W+rLUsIpzpERPsvwUP7CckAQSOoA==";
      };
    };
    "lru.min-1.1.2" = {
      name = "lru.min";
      packageName = "lru.min";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru.min/-/lru.min-1.1.2.tgz";
        sha512 = "Nv9KddBcQSlQopmBHXSsZVY5xsdlZkdH/Iey0BlcBYggMd4two7cZnKOK9vmy3nY0O5RGH99z1PCeTpPqszUYg==";
      };
    };
    "mysql2-3.14.3" = {
      name = "mysql2";
      packageName = "mysql2";
      version = "3.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mysql2/-/mysql2-3.14.3.tgz";
        sha512 = "fD6MLV8XJ1KiNFIF0bS7Msl8eZyhlTDCDl75ajU5SJtpdx9ZPEACulJcqJWr1Y8OYyxsFc4j3+nflpmhxCU5aQ==";
      };
    };
    "named-placeholders-1.1.3" = {
      name = "named-placeholders";
      packageName = "named-placeholders";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/named-placeholders/-/named-placeholders-1.1.3.tgz";
        sha512 = "eLoBxg6wE/rZkJPhU/xRX1WTpkFEwDJEN96oxFrTsqBdbT5ec295Q+CoHrL9IT0DipqKhmGcaZmwOt8OON5x1w==";
      };
    };
    "node-sql-parser-5.3.11" = {
      name = "node-sql-parser";
      packageName = "node-sql-parser";
      version = "5.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-sql-parser/-/node-sql-parser-5.3.11.tgz";
        sha512 = "1ZcXu2qEFZlMkkaYPpMoTkypTunYTvtnInzVjWDhjc1+FS5h/WqT1rbgP2pP42/nXBWfPVN66mEfidWSpYVs1Q==";
      };
    };
    "raw-body-3.0.0" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-3.0.0.tgz";
        sha512 = "RmkhL8CAyCRPXCE28MMH0z2PNWQBNk2Q09ZdxM9IOOXwxwZbN+qbWaatPkdkWIKL2ZVDImrN/pK5HTRz2PcS4g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "seq-queue-0.0.5" = {
      name = "seq-queue";
      packageName = "seq-queue";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/seq-queue/-/seq-queue-0.0.5.tgz";
        sha512 = "hr3Wtp/GZIc/6DAGPDcV4/9WoZhjrkXsi5B/07QgX8tsdc6ilr7BFM6PM6rbdAX1kFSDYeZGLipIZZKyQP0O5Q==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "sqlstring-2.3.3" = {
      name = "sqlstring";
      packageName = "sqlstring";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sqlstring/-/sqlstring-2.3.3.tgz";
        sha512 = "qC9iz2FlN7DQl3+wjwn3802RTyjCx7sDvfQEXchwa6CWOx07/WVfh91gBmQ9fahw8snwGEWU3xGzOt4tFyHLxg==";
      };
    };
    "statuses-2.0.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-2.0.1.tgz";
        sha512 = "RwNA9Z/7PrK06rYLIzFMlaF+l73iwpzsqRIFgbMLbTcLD6cOao82TaWefPXQvB2fOC4AjuYSEndS7N/mTCbkdQ==";
      };
    };
    "toidentifier-1.0.1" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
        sha512 = "o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha512 = "pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==";
      };
    };
    "zod-3.25.76" = {
      name = "zod";
      packageName = "zod";
      version = "3.25.76";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
        sha512 = "gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
      };
    };
  };
in
{
  yii2-mcp-server = nodeEnv.buildNodePackage {
    name = "yii2-mcp-server";
    packageName = "yii2-mcp-server";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/yii2-mcp-server/-/yii2-mcp-server-1.0.2.tgz";
      sha512 = "QKbQI8c+0910E1mqwQACwgtvGVLZMkjtFuq2Z0QXcOImWwLk1jHKIw0z95dvC/NrBieVYyRnDdDLMwoYFlc62A==";
    };
    dependencies = [
      sources."@modelcontextprotocol/sdk-0.6.1"
      sources."@types/pegjs-0.10.6"
      sources."aws-ssl-profiles-1.1.2"
      sources."big-integer-1.6.52"
      sources."bytes-3.1.2"
      sources."content-type-1.0.5"
      sources."denque-2.1.0"
      sources."depd-2.0.0"
      sources."generate-function-2.3.1"
      sources."http-errors-2.0.0"
      sources."iconv-lite-0.6.3"
      sources."inherits-2.0.4"
      sources."is-property-1.0.2"
      sources."long-5.3.2"
      sources."lru-cache-7.18.3"
      sources."lru.min-1.1.2"
      sources."mysql2-3.14.3"
      sources."named-placeholders-1.1.3"
      sources."node-sql-parser-5.3.11"
      sources."raw-body-3.0.0"
      sources."safer-buffer-2.1.2"
      sources."seq-queue-0.0.5"
      sources."setprototypeof-1.2.0"
      sources."sqlstring-2.3.3"
      sources."statuses-2.0.1"
      sources."toidentifier-1.0.1"
      sources."unpipe-1.0.0"
      sources."zod-3.25.76"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "MCP Server for Yii2 Framework - Database schema inspection, command execution, and project management";
      homepage = "https://github.com/ArtMin96/yii2-mcp-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
